
name: Synchronize to forked repo
on:
push:
branches:
  - main

jobs:
sync:
name: Sync forked repo
runs-on: ubuntu-latest

steps:
- name: Checkout main 
uses: actions/checkout@v4 
- name: Use Node.js 
uses: actions/setup-node@v4 
	with:
		node-version: 21.4.0 

	- name: Install dependencies 
	run: yarn install

	- name: Build project 
	run: yarn run build

	- name: Add remote-url
	run: |
		git remote add forked-repo https://exceptanyone:${{ secrets.FORKED_REPO_TOKEN }}@github.com/exceptanyone/github-action-practice
		git config user.name exceptanyone
		git config user.email wjddks96@naver.com

	- name: Push changes to forked-repo 
	run: |
		git push -f forked-repo main

	- name: Clean up 
	run: |
		git remote remove forked-repo